# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: 'apps/gateway'
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'npm'
    directory: 'apps/native'
    schedule:
      interval: 'monthly'
    ignore:
      - dependency-name: '*expo*'
      - dependency-name: 'lottie-react-native'
      - dependency-name: 'react'
      - dependency-name: 'react-native'
      - dependency-name: 'react-dom'
      - dependency-name: 'react-native-svg'
      - dependency-name: 'react-native-screens'
      - dependency-name: 'react-native-gesture-handler'
      - dependency-name: 'react-native-safe-area-context'
      - dependency-name: 'react-native-reanimated'
      - dependency-name: 'react-native-pager-view'
      - dependency-name: 'react-native-webview'
      - dependency-name: '@shopify/react-native-skia'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: 'packages/*'
    schedule:
      interval: 'monthly'
