name: Update licenses.json
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
    paths:
      - 'apps/native/package.json'
  workflow_dispatch:

jobs:
  update-licenses:
    name: Update app licenses.json
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.REPO_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Update licenses.json
        working-directory: ./apps/native
        run: yarn generate:licenses

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update licenses.json'
          branch: ${{ github.head_ref }}
