name: bff-build

on:
  workflow_call:
    inputs:
      tag_version:
        description: 'Should a version tag be added to the image'
        required: false
        type: boolean
        default: false

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: bovracontainers.azurecr.io
          username: bovracontainers
          password: ${{ secrets.ACR_PASSWORD }}

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: apps/gateway

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/bovra/bovra.frontend.gateway
            bovracontainers.azurecr.io/bovra/bovra.frontend.gateway
          tags: |
            type=semver,pattern={{version}},value=${{steps.package-version.outputs.current-version}},enable=${{inputs.tag_version}}
            type=sha
            type=raw,value=latest

      - name: Build image and push to container registry
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./
          file: ./apps/gateway/Dockerfile
          build-args: |
            TURBO_TEAM=${{ secrets.TURBO_TEAM }}
            TURBO_TOKEN=${{ secrets.TURBO_TOKEN }}
          cache-from: type=gha,scope=bovra-frontend-gateway
          cache-to: type=gha,scope=bovra-frontend-gateway,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

