name: bff-staging-deploy

on:
  workflow_call:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: bff-staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: benjlevesque/short-sha@v3.0
        id: short-sha

      - name: Deploy to azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: bovracontainers.azurecr.io/bovra/bovra.frontend.gateway:sha-${{ steps.short-sha.outputs.sha }}
          slot-name: ${{ vars.AZURE_WEBAPP_SLOT_NAME }}

