name: ci

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  check:
    name: check
    strategy:
      matrix:
        command: [types, test]
    runs-on: linux-big
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Build deps
        run: yarn build:packages

      - name: Static types
        working-directory: apps/native
        run: npx expo customize tsconfig.json

      - name: Run command
        run: yarn ${{ matrix.command }}

  lint:
    name: lint
    runs-on: linux-big
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Build deps
        run: yarn build:packages

      - name: Static types
        working-directory: apps/native
        run: npx expo customize tsconfig.json

      - name: Lint code
        run: yarn lint
        env:
          ESLINT_USE_FLAT_CONFIG: true

  graphql:
    name: check (graphql)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: kamilkisiela/graphql-inspector@v3.4.0
        with:
          schema: 'main:apps/gateway/schemas/schema.gql'
          approve-label: expected-breaking-graphql-change
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_PAT }}

  prettify:
    name: prettify
    needs: check
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v43
        with:
          files: |
            apps/**/src/**
            packages/**/src/**

      - name: Wrapped file paths
        id: wrapped-file-paths
        run: |
          WRAPPED_PATHS=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | sed "s/\([^ ]*\)/'\1'/g")
          echo "WRAPPED_PATHS=$WRAPPED_PATHS" >> $GITHUB_ENV

      - name: Prettify code
        run: yarn format $WRAPPED_PATHS --no-error-on-unmatched-pattern

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: prettier'
          branch: ${{ github.head_ref }}
