name: dev-deployment
concurrency:
    group: dev-deployment-${{ github.ref }}
    cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - 'apps/gateway/**'
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: bovracontainers.azurecr.io
          username: bovracontainers
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/bovra/bovra.frontend.gateway
            bovracontainers.azurecr.io/bovra/bovra.frontend.gateway
          tags: |
            type=sha
            type=raw,value=develop

      - name: Build image and push to container registry
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./
          file: ./apps/gateway/Dockerfile
          build-args: |
            TURBO_TEAM=${{ secrets.TURBO_TEAM }}
            TURBO_TOKEN=${{ secrets.TURBO_TOKEN }}
          cache-from: type=gha,scope=bovra-frontend-gateway
          cache-to: type=gha,scope=bovra-frontend-gateway,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build
    environment: bff-dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: benjlevesque/short-sha@v3.0
        id: short-sha

      - name: Deploy to azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: bovracontainers.azurecr.io/bovra/bovra.frontend.gateway:sha-${{ steps.short-sha.outputs.sha }}
          slot-name: ${{ vars.AZURE_WEBAPP_SLOT_NAME }}
